Feature/preview in floating window
stevearc/oil.nvim pull request #403
Opened 2024-06-03 22:18 UTC by PhilippOesch

Because I'm a big fan of the floating window, but also of the preview functionality.

This implements #303

2024-06-06 21:32 UTC, stevearc requested changes
Visually looks great! Needs stylua applied and some of the tests are no longer passing. I also noticed some bugs if you open oil + preview, then `:tabnew` and open oil + preview again.

Will provide a more thorough code review after these things are addressed

2024-06-06 21:32 UTC, stevearc commented on lua/oil/config.lua
> +    preview_split = 'left',
I think the default should be `"auto"`, which choose left/right based on the value of `vim.o.splitright`

2024-06-18 03:03 UTC, stevearc commented
@PhilippOesch I moved some of the logic around and did some other various refactoring. Take a look, kick the tires, and if you're happy with it I'll merge!

2024-06-19 19:09 UTC, PhilippOesch commented
> @PhilippOesch I moved some of the logic around and did some other various refactoring. Take a look, kick the tires, and if you're happy with it I'll merge!

The refactoring looks good from my view. Thank you for taking your time and looking at it. If you want, you can merge.

2024-06-20 01:23 UTC, merged