feat: disable preview for large files
stevearc/oil.nvim pull request #511
Opened 2024-11-08 12:53 UTC by stevalkr

- #213 

Hi, I’ve made a small change to prevent nvim session from freezing when previewing large files.

2024-11-11 00:10 UTC, stevearc requested changes
Change looks good, but I've had to refactor a bunch of the config names recently to reduce confusion. You'll need to rebase to resolve the merge conflicts.

2024-11-11 00:10 UTC, stevearc commented on README.md
> +    max_file_size = 100,
Could we use the units in the name? Something like `max_file_size_mb`

2024-11-11 17:03 UTC, stevearc commented
typechecking errors. If you have LuaLS installed you can run `make lint` to view to run it locally

2024-11-12 09:12 UTC, stevalkr commented
Sorry about that, I didn’t check all the changes thoroughly. Should be all good now.

2024-11-12 16:24 UTC, stevearc commented
Thanks for the PR!

2024-11-12 16:24 UTC, merged